#it can use for another directory
port = "8001"
public_dir = "."
index_file = "index.html"
cache_control = 10

[[conditions]]
source = 'api'
dest = 'http://127.0.0.1:3000/'

[[conditions]]
source = '11'
dest = '2'
