CREATE TABLE IF NOT EXISTS cells (
    x INT,
    y INT,
    user_id INT NOT NULL,
    building VARCHAR(200) NOT NULL,
    score INT NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	PRIMARY KEY (x, y),
	INDEX idx_user_id (user_id)
);
