environment: development
app_name: dimoklan
app_url: "http://127.0.0.1:3000/"
port: ":3000"

# secrets
salt: "z2nklIqBZ8KN+=7nLEQ19@7.P"
jwt_secret: "c810ab3a3f819301a23e9751c9810a41b0b1d4ea"

# language
default_lang: ku
original_error: true

# log
log_path: /home/diako/projects/dimoklan/server/logs/basic_dimoklan.log
log_level: debug


# map storage
map_dynamodb_region: "us-west-2"
map_dynamodb_endpoint: "http://127.0.0.1:8000"
map_aws_access_key_id: "fake_key"
map_aws_secret_access_key: "fake_secret"

# redis connection
redis_addr: "redis-11793.c135.eu-central-1-1.ec2.redns.redis-cloud.com:11793"
redis_password: "Qsfqv0EChzRroSaovA9de9PzSPCdhGx6"
redis_db: 0

# global
login_page: "http://127.0.0.1:3000/login"

# mailjet
mj_apikey_public: "4107cf574139d1e1455244bfa94df2db"
mj_apikey_private: "e8fc130d3a5393784fe81a8ce8dabf7a"
